- name: Test of Packet project module
  hosts: localhost
  vars:
    tmpname: "Temp project"
  tasks:

  - packet_project:
      name: "{{ tmpname}}"
      state: absent
    register: result

  - packet_project:
      name: "{{ tmpname}}"
      state: present
    register: result

  - name: assert changed is True
    assert:
      that:
        - result.changed == True

  - packet_project:
      name: "{{ tmpname}}"
      state: present
    register: result

  - name: assert changed is False
    assert:
      that:
        - result.changed == False

  - packet_project:
      id: "{{ result.id }}"
      state: absent
    register: result

  - name: assert changed is True
    assert:
      that:
        - result.changed == True


