- name: Test IP address assignment
  hosts: localhost
  vars:
    project_id: 52000fb2-ee46-4673-93a8-de2c2bdba33b
    devname: testserver
# Pick an address from a block allocated to your project.
    address: 147.75.69.252
  tasks:
  - packet_device:
      project_id: "{{ project_id }}"
      hostnames:  "{{ devname }}"
      operating_system: ubuntu_16_04
      plan: baremetal_0
      facility: sjc1

# NOTE: if you want to assign the IP address, you should make sure that the
# device is in "active" state.

  - packet_ip_address:
      project_id: "{{ project_id }}"
      hostname:   "{{ devname }}"
      ip_address: "{{ address }}"
      state: absent
    register: result

  - packet_ip_address:
      project_id: "{{ project_id }}"
      hostname:   "{{ devname }}"
      ip_address: "{{ address }}"
    register: result

  - name: assert changed is True
    assert:
      that:
      - result.changed == True

  - packet_ip_address:
      project_id: "{{ project_id }}"
      hostname:   "{{ devname }}"
      ip_address: "{{ address }}"
    register: result

  - name: assert changed is False
    assert:
      that:
      - result.changed == False


  - packet_ip_address:
      project_id: "{{ project_id }}"
      ip_address: "{{ address }}"
      state: absent
    register: result

  - name: assert changed is True
    assert:
      that:
      - result.changed == True

  - packet_ip_address:
      project_id: "{{ project_id }}"
      hostname:   "{{ devname }}"
      ip_address: "{{ address }}"
    register: result

  - name: assert changed is True
    assert:
      that:
      - result.changed == True

  - packet_ip_address:
      project_id: "{{ project_id }}"
      device_id:   "{{ result.device_id }}"
      ip_address: "{{ address }}"
      state: absent
    register: result

  - name: assert changed is True
    assert:
      that:
      - result.changed == True

