- hosts: localhost
  vars:
    volname: testvol123
    project_id: 52000fb2-ee46-4673-93a8-de2c2bdba33b

  tasks:
    - name: remove volume in case there is one from previous runs
      packet_volume:
        description: "{{ volname }}"
        project_id: "{{ project_id }}"
        state: absent

    - name: test create volume
      packet_volume:
        description: "{{ volname }}"
        project_id: "{{ project_id }}"
        facility: 'ewr1'
        plan: 'storage_1'
        state: present
        size: 10
        snapshot_policy:
          snapshot_count: 10
          snapshot_frequency: 1day
      register: result_create

    - name: assert changed is True
      assert:
        that:
          - result_create.changed == True

    - name: test create volume (idempotent)
      packet_volume:
        description: "{{ volname }}"
        project_id: "{{ project_id }}"
        state: present
      register: result

    - name: assert changed is False
      assert:
        that:
          - result.changed == False

    - name: test delete volume
      packet_volume:
        id: "{{ result_create.id }}"
        project_id: "{{ project_id }}"
        state: absent
      register: result

    - name: assert changed is True
      assert:
        that:
          - result.changed == True
